// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {AgriFlowEscrow} from "../src/AgriFlowEscrow.sol";
import {AgriFlowGasMaster} from "../src/AgriFlowGasMaster.sol";
import {IAgriFlowEscrow} from "../src/interfaces/IAgriFlowEscrow.sol";
import {IAgriFlowGasMaster} from "../src/interfaces/IAgriFlowGasMaster.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/**
 * @title AgriFlowIntentIntegrationTest
 * @notice Tests Flow A: Direct to Smart Contract (NEAR Intent solver -> AgriFlowEscrow -> Gasless Delivery & Pull Withdrawals)
 */
contract AgriFlowIntentIntegrationTest is Test {
    AgriFlowEscrow public escrow;
    AgriFlowGasMaster public gasMaster;
    MockERC20 public usdc;

    address public treasury = 0x41648dE45Cc4D0172beCd4Db0A0A0b459C383705;
    address public relayer = 0x41648dE45Cc4D0172beCd4Db0A0A0b459C383705;

    uint256 public buyerPk = 0xB0B1;
    address public buyer;

    address public supplier = makeAddr("supplier_farmer");
    address public logistics = makeAddr("logistics_hauler");
    address public nearSolver = makeAddr("near_solver");

    // Address generated by NEAR 1-Click Intent API
    address public intentGeneratedDepositAddress = 0x1111222233334444555566667777888899990000;
    bytes32 public tradeId = keccak256("AGRIFLOW-CORN-TRADE-2026-001");
    string public nearIntentTxHash = "9hXyVjT3PqU8vN1kLmWs7zBcDeFgHjKlMnOpQrStUvWx";

    // Amounts (USDC 6 decimals)
    uint256 public goodsAmount = 10_000 * 1e6;     // $10,000 to farmer
    uint256 public logisticsAmount = 800 * 1e6;    // $800 to hauler
    uint256 public platformFee = 108 * 1e6;        // 1% platform fee to treasury
    uint256 public totalEscrowLocked = 10_908 * 1e6; // $10,908 total

    bytes32 public constant FORWARD_REQUEST_TYPEHASH = keccak256(
        "ForwardRequest(address from,address to,uint256 value,uint256 gas,uint256 nonce,uint256 deadline,bytes data)"
    );

    function setUp() public {
        buyer = vm.addr(buyerPk);

        address[] memory initialTargets = new address[](0);
        gasMaster = new AgriFlowGasMaster(treasury, initialTargets);
        escrow = new AgriFlowEscrow(treasury, relayer, address(gasMaster));

        vm.prank(treasury);
        gasMaster.setTargetWhitelist(address(escrow), true);

        // Pre-fund GasMaster gas tank for relayer gas refunds
        vm.deal(address(gasMaster), 10 ether);

        usdc = new MockERC20("USD Coin", "USDC", 6);

        // Solver / Relayer receives funds from cross-chain swap
        usdc.mint(relayer, 1_000_000 * 1e6);
        vm.prank(relayer);
        usdc.approve(address(escrow), type(uint256).max);
    }

    function test_EndToEnd_Intent_DirectToEscrow_GaslessConfirmation() public {
        // --- STEP 1: NEAR Intent Fulfill -> Funds Direct to AgriFlowEscrow ---
        // Verify contract initial state
        assertEq(usdc.balanceOf(address(escrow)), 0);

        // Relayer executes fundTradeFromIntent when NEAR solver completes cross-chain intent
        vm.prank(relayer);
        escrow.fundTradeFromIntent(
            tradeId,
            buyer,
            supplier,
            logistics,
            address(usdc),
            intentGeneratedDepositAddress,
            nearIntentTxHash,
            goodsAmount,
            logisticsAmount,
            platformFee
        );

        // Invariant: Funds are securely locked in the smart contract vault
        assertEq(usdc.balanceOf(address(escrow)), totalEscrowLocked);

        // Verify stored trade data & cryptographic hash
        IAgriFlowEscrow.Trade memory trade = escrow.getTrade(tradeId);
        assertEq(uint8(trade.status), uint8(IAgriFlowEscrow.TradeStatus.FUNDED));
        assertEq(trade.generatedDepositAddress, intentGeneratedDepositAddress);
        assertEq(trade.intentTxHash, nearIntentTxHash);

        bytes32 expectedDetailsHash = escrow.computeTradeHash(
            tradeId,
            buyer,
            supplier,
            logistics,
            goodsAmount,
            logisticsAmount,
            intentGeneratedDepositAddress
        );
        assertEq(trade.detailsHash, expectedDetailsHash);

        // --- STEP 2: Buyer Gasless Meta-Transaction Delivery Confirmation ---
        // Buyer has 0 ETH in their wallet
        vm.deal(buyer, 0);
        assertEq(buyer.balance, 0);

        bytes memory confirmCalldata = abi.encodeWithSelector(IAgriFlowEscrow.confirmDelivery.selector, tradeId);

        IAgriFlowGasMaster.ForwardRequest memory req = IAgriFlowGasMaster.ForwardRequest({
            from: buyer,
            to: address(escrow),
            value: 0,
            gas: 200_000,
            nonce: gasMaster.getNonce(buyer),
            deadline: block.timestamp + 1 days,
            data: confirmCalldata
        });

        // Sign EIP-712 forward request off-chain with Buyer's private key
        bytes memory signature = _signEip712(buyerPk, req);

        // Relayer submits the signed meta-tx to AgriFlowGasMaster
        vm.deal(relayer, 5 ether);
        vm.prank(relayer);
        (bool success, ) = gasMaster.execute(req, signature);
        assertTrue(success, "Gasless meta-transaction execution failed");

        // Buyer still spent 0 ETH!
        assertEq(buyer.balance, 0);

        // Contract status transitioned to COMPLETED
        trade = escrow.getTrade(tradeId);
        assertEq(uint8(trade.status), uint8(IAgriFlowEscrow.TradeStatus.COMPLETED));

        // --- STEP 3: Multi-Party Pull Vault Distribution ---
        // Verify internal credited balances
        assertEq(escrow.getWithdrawableBalance(supplier, address(usdc)), goodsAmount);
        assertEq(escrow.getWithdrawableBalance(logistics, address(usdc)), logisticsAmount);
        assertEq(escrow.getWithdrawableBalance(treasury, address(usdc)), platformFee);

        // Supplier withdraws goods amount ($10,000)
        vm.prank(supplier);
        escrow.withdraw(address(usdc));
        assertEq(usdc.balanceOf(supplier), goodsAmount);
        assertEq(escrow.getWithdrawableBalance(supplier, address(usdc)), 0);

        // Logistics carrier withdraws haulage fee ($800)
        vm.prank(logistics);
        escrow.withdraw(address(usdc));
        assertEq(usdc.balanceOf(logistics), logisticsAmount);
        assertEq(escrow.getWithdrawableBalance(logistics, address(usdc)), 0);

        // Treasury withdraws 1% platform fee ($108)
        uint256 treasuryPre = usdc.balanceOf(treasury);
        vm.prank(treasury);
        escrow.withdraw(address(usdc));
        assertEq(usdc.balanceOf(treasury), treasuryPre + platformFee);
        assertEq(escrow.getWithdrawableBalance(treasury, address(usdc)), 0);

        // Final Invariant: Total escrow balance is now 0 after full payout
        assertEq(usdc.balanceOf(address(escrow)), 0);
    }

    function _signEip712(
        uint256 privateKey,
        IAgriFlowGasMaster.ForwardRequest memory req
    ) internal view returns (bytes memory) {
        (, string memory name, string memory version, uint256 chainId, address verifyingContract, , ) = gasMaster
            .eip712Domain();

        bytes32 domainSeparator = keccak256(
            abi.encode(
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256(bytes(name)),
                keccak256(bytes(version)),
                chainId,
                verifyingContract
            )
        );

        bytes32 structHash = keccak256(
            abi.encode(
                FORWARD_REQUEST_TYPEHASH,
                req.from,
                req.to,
                req.value,
                req.gas,
                req.nonce,
                req.deadline,
                keccak256(req.data)
            )
        );

        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domainSeparator, structHash));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(privateKey, digest);
        return abi.encodePacked(r, s, v);
    }
}
