// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IAgriFlowEscrow
 * @notice Interface for the AgriFlow Multi-Party Vault Escrow with generated address tracking and cryptographic trade hashing.
 */
interface IAgriFlowEscrow {
    enum TradeStatus {
        NONE,
        FUNDED,
        COMPLETED,
        DISPUTED,
        REFUNDED
    }

    struct Trade {
        bytes32 tradeId;
        address buyer;
        address supplier;
        address logistics;
        address token;                   // address(0) for native ETH, or ERC20 (e.g. USDC)
        address generatedDepositAddress; // Unique deposit wallet generated by Intent API
        bytes32 detailsHash;             // keccak256 cryptographic hash of transaction details
        string intentTxHash;             // Proof of deposit transaction hash
        uint256 goodsAmount;             // Payable to Supplier
        uint256 logisticsAmount;         // Payable to Logistics Carrier
        uint256 platformFee;             // Platform Fee (e.g. 1%)
        TradeStatus status;
        uint256 createdAt;
        uint256 fundedAt;
    }

    // --- Events ---

    event TradeFunded(
        bytes32 indexed tradeId,
        address indexed buyer,
        address indexed supplier,
        address logistics,
        address token,
        uint256 totalAmount,
        address generatedDepositAddress,
        bytes32 detailsHash,
        string intentTxHash
    );

    event DeliveryConfirmed(bytes32 indexed tradeId, address indexed buyer);

    event FundsCredited(
        bytes32 indexed tradeId,
        address indexed recipient,
        address token,
        uint256 amount
    );

    event Withdrawn(address indexed recipient, address indexed token, uint256 amount);

    event TradeDisputed(bytes32 indexed tradeId, address indexed caller);

    event BuyerRefunded(bytes32 indexed tradeId, address indexed buyer, uint256 refundAmount);

    event RelayerUpdated(address indexed oldRelayer, address indexed newRelayer);

    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);

    // --- Custom Errors ---

    error TradeAlreadyExists(bytes32 tradeId);
    error TradeNotFound(bytes32 tradeId);
    error InvalidTradeStatus(bytes32 tradeId, TradeStatus current, TradeStatus expected);
    error UnauthorizedCaller(address caller);
    error ZeroAddress();
    error InvalidAmount();
    error InsufficientPayment(uint256 sent, uint256 required);
    error NoWithdrawableBalance();

    // --- Functions ---

    function computeTradeHash(
        bytes32 tradeId,
        address buyer,
        address supplier,
        address logistics,
        uint256 goodsAmount,
        uint256 logisticsAmount,
        address generatedDepositAddress
    ) external pure returns (bytes32);

    function fundTradeFromIntent(
        bytes32 tradeId,
        address buyer,
        address supplier,
        address logistics,
        address token,
        address generatedDepositAddress,
        string calldata intentTxHash,
        uint256 goodsAmount,
        uint256 logisticsAmount,
        uint256 platformFee
    ) external payable;

    function confirmDelivery(bytes32 tradeId) external;

    function withdraw(address token) external;

    function withdrawETH() external;

    function raiseDispute(bytes32 tradeId) external;

    function refundBuyer(bytes32 tradeId) external;

    function getTrade(bytes32 tradeId) external view returns (Trade memory);

    function getWithdrawableBalance(address user, address token) external view returns (uint256);
}
